module.exports = [
  { marca: "Ferrari", modelo: "Enzo", anio: 2002 },
  { marca: "Porsche", modelo: "Carrera GT", anio: 2004 },
  { marca: "Mercedes-Benz", modelo: "SLR McLaren", anio: 2003 },
  { marca: "Aston Martin", modelo: "One-77", anio: 2009 },
  { marca: "Lexus", modelo: "IS F", anio: 2007 },
  { marca: "Alfa Romeo", modelo: "4C", anio: 2013 },
  { marca: "BMW", modelo: "M4 F82", anio: 2014 },
  { marca: "Audi", modelo: "RS4 Avant B5", anio: 2000 },
  { marca: "Nissan", modelo: "Silvia S15", anio: 1999 },
  { marca: "Toyota", modelo: "Celica GT-Four", anio: 1994 },
  { marca: "Mitsubishi", modelo: "Eclipse GSX", anio: 1995 },
  { marca: "Honda", modelo: "CR-X Si", anio: 1989 },
  { marca: "Volkswagen", modelo: "Corrado VR6", anio: 1992 },
  { marca: "Ford", modelo: "Focus RS Mk1", anio: 2002 },
  { marca: "Renault", modelo: "Megane RS R26.R", anio: 2008 },
  { marca: "Peugeot", modelo: "106 Rallye", anio: 1993 },
  { marca: "Fiat", modelo: "Uno Turbo i.e.", anio: 1985 },
  { marca: "Opel", modelo: "Kadett GSi", anio: 1984 },
  { marca: "Seat", modelo: "Cordoba WRC", anio: 1998 },
  { marca: "Lancia", modelo: "037 Stradale", anio: 1982 },
  { marca: "Subaru", modelo: "SVX", anio: 1991 },
  { marca: "Mazda", modelo: "RX-8", anio: 2003 },
  { marca: "Suzuki", modelo: "Cappuccino", anio: 1991 },
  { marca: "Daihatsu", modelo: "Copen", anio: 2002 },
  { marca: "Honda", modelo: "Beat", anio: 1991 },
  { marca: "Autozam", modelo: "AZ-1", anio: 1992 },
  { marca: "Toyota", modelo: "MR2 SW20", anio: 1989 },
  { marca: "Pontiac", modelo: "Firebird Trans Am", anio: 1977 },
  { marca: "Chevrolet", modelo: "Chevelle SS", anio: 1970 },
  { marca: "Plymouth", modelo: "Barracuda", anio: 1970 },
  { marca: "Dodge", modelo: "Viper RT/10", anio: 1992 },
  { marca: "Ford", modelo: "Sierra RS Cosworth", anio: 1986 },
  { marca: "Vauxhall", modelo: "Lotus Carlton", anio: 1990 },
  { marca: "Jaguar", modelo: "XKR", anio: 1998 },
  { marca: "Bentley", modelo: "Turbo R", anio: 1985 },
  { marca: "Rolls-Royce", modelo: "Ghost", anio: 2009 },
  { marca: "Maserati", modelo: "Quattroporte V", anio: 2003 },
  { marca: "Ferrari", modelo: "Testarossa", anio: 1984 },
  { marca: "Lamborghini", modelo: "Diablo", anio: 1990 },
  { marca: "Bugatti", modelo: "EB110", anio: 1991 },
  { marca: "Jaguar", modelo: "D-Type", anio: 1954 },
  { marca: "Aston Martin", modelo: "V12 Vantage", anio: 2009 },
  { marca: "McLaren", modelo: "720S", anio: 2017 },
  { marca: "Porsche", modelo: "930 Turbo", anio: 1975 },
  { marca: "BMW", modelo: "Z8", anio: 2000 },
  { marca: "Mercedes-Benz", modelo: "SLS AMG", anio: 2010 },
  { marca: "Audi", modelo: "Sport Quattro", anio: 1984 },
  { marca: "Volkswagen", modelo: "Scirocco", anio: 1974 },
  { marca: "Volvo", modelo: "240 Turbo", anio: 1981 },
  { marca: "Saab", modelo: "9-3 Viggen", anio: 1999 },
  { marca: "Alfa Romeo", modelo: "GTV6", anio: 1980 },
  { marca: "Lancia", modelo: "Thema 8.32", anio: 1986 },
  { marca: "Fiat", modelo: "Coupe 20V Turbo", anio: 1996 },
  { marca: "Peugeot", modelo: "206 RC", anio: 2003 },
  { marca: "Renault", modelo: "Clio Williams", anio: 1993 },
  { marca: "Citroen", modelo: "Saxo VTS", anio: 1996 },
  { marca: "MG", modelo: "MGB", anio: 1962 },
  { marca: "Triumph", modelo: "TR6", anio: 1968 },
  { marca: "Austin-Healey", modelo: "3000", anio: 1959 },
  { marca: "Lotus", modelo: "Elise S1", anio: 1996 },
  { marca: "TVR", modelo: "Sagaris", anio: 2004 },
  { marca: "Morgan", modelo: "Plus 8", anio: 1968 },
  { marca: "Caterham", modelo: "7", anio: 1973 },
  { marca: "Ariel", modelo: "Atom", anio: 2000 },
  { marca: "KTM", modelo: "X-Bow", anio: 2008 },
  { marca: "BAC", modelo: "Mono", anio: 2011 },
  { marca: "Radical", modelo: "SR3", anio: 2001 },
  { marca: "Pagani", modelo: "Huayra", anio: 2011 },
  { marca: "Koenigsegg", modelo: "Agera RS", anio: 2015 },
  { marca: "Spyker", modelo: "C8", anio: 2000 },
  { marca: "Noble", modelo: "M600", anio: 2010 },
  { marca: "Saleen", modelo: "S7", anio: 2000 },
  { marca: "SSC", modelo: "Tuatara", anio: 2020 },
  { marca: "Hennessey", modelo: "Venom F5", anio: 2020 },
  { marca: "Rimac", modelo: "Nevera", anio: 2021 },
  { marca: "Pininfarina", modelo: "Battista", anio: 2020 },
  { marca: "Lotus", modelo: "Evija", anio: 2020 },
  { marca: "Tesla", modelo: "Roadster", anio: 2008 },
  { marca: "Porsche", modelo: "Taycan Turbo S", anio: 2019 },
  { marca: "Audi", modelo: "RS e-tron GT", anio: 2021 },
  { marca: "Polestar", modelo: "1", anio: 2019 },
  { marca: "BMW", modelo: "i8", anio: 2014 },
  { marca: "Honda", modelo: "NSX NC1", anio: 2016 },
  { marca: "Nissan", modelo: "GT-R R35", anio: 2007 },
  { marca: "Toyota", modelo: "GR Yaris", anio: 2020 },
  { marca: "Subaru", modelo: "WRX STI", anio: 2014 },
  { marca: "Mitsubishi", modelo: "Lancer Evolution X", anio: 2007 },
  { marca: "Ford", modelo: "Fiesta ST", anio: 2013 },
  { marca: "Hyundai", modelo: "Veloster N", anio: 2019 },
  { marca: "Kia", modelo: "ProCeed GT", anio: 2013 },
  { marca: "Seat", modelo: "Leon Cupra 290", anio: 2016 },
  { marca: "Skoda", modelo: "Superb V6", anio: 2001 },
  { marca: "Dacia", modelo: "Duster", anio: 2010 },
  { marca: "Lada", modelo: "Niva", anio: 1977 },
  { marca: "UAZ", modelo: "469", anio: 1971 },
  { marca: "Hummer", modelo: "H1", anio: 1992 },
  { marca: "GMC", modelo: "Syclone", anio: 1991 },
  { marca: "Ford", modelo: "F-150 SVT Lightning", anio: 1999 },
  { marca: "Dodge", modelo: "Ram SRT-10", anio: 2004 },
  { marca: "Chevrolet", modelo: "El Camino SS", anio: 1970 }
];